### ISSUE TITLE
Consider changing name of the repository

### ISSUE THREAD

**Issue by frederickjh** [xxh/xxh-shell-example#1]
**Is your feature request related to a problem? Please describe.**
Consider changing **sample ** in the repository name to **example**. I believe the term example is a easier to understand and more commonly used for repositories that are used to be an example of how to build a new one.

The word **sample** means, a small random piece of something.
The word **example** means, something that is specific and illustrates or demonstrates something.

**Describe the solution you'd like**
Rename the repository from `xxh/xxh-shell/sample` to  `xxh/xxh-shell/example`.

**Describe alternatives you've considered**
none

**Additional context**
[What is the difference between example and sample?](https://wikidiff.com/example/sample)
[Difference Between Example and Sample](http://www.differencebetween.net/language/words-language/difference-between-example-and-sample/)

**For community:**
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by anki-code** [comment]
All xxh family repos renamed from sample to example.
